# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2016 Serpent Consulting Services Pvt. Ltd.
#    (<http://www.serpentcs.com>)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from openerp import models,fields,api


class res_company(models.Model):
    
    _inherit = 'res.company'

    header = """
    <header>
    <pageTemplate>
        <frame id="first" x1="1.3cm" y1="3.0cm" height="21.7cm" width="19.0cm"/>
         <stylesheet>
            <!-- Set here the default font to use for all <para> tags -->
            <paraStyle name='Normal' fontName="DejaVuSans"/>
          <paraStyle name="terp_default_left_9_Bold" fontName="Helvetica-Bold" fontSize="9.0" leading="11" alignment="LEFT"          spaceBefore="0.0" spaceAfter="0.0"/> 
          <paraStyle name="terp_default_right_9_Bold" fontName="Helvetica-Bold" fontSize="9.0" leading="11" alignment="RIGHT"          spaceBefore="0.0" spaceAfter="0.0"/> 
            <paraStyle name="main_footer" fontSize="8.0" alignment="CENTER"/>
            <paraStyle name="main_header" fontSize="8.0" leading="10" alignment="LEFT" spaceBefore="0.0" spaceAfter="0.0"/>
         </stylesheet>
        <pageGraphics>
            <!-- Set here the default font to use for all <drawString> tags -->
            <setFont name="DejaVuSans" size="8"/>
            <!-- You Logo - Change X,Y,Width and Height -->
            <image x="1.3cm" y="27.7cm" height="40.0" >[[ company.logo or removeParentNode('image') ]]</image>
            <fill color="black"/>
            <stroke color="black"/>

            <!-- page header -->
            <drawString style="terp_default_left_9_Bold" x="13cm" y="29.0cm">[[ company.name ]]</drawString>
            <drawString style="terp_default_left_9_Bold" x="13cm" y="28.6cm">[[ company.partner_id.street or '' ]], [[ company.partner_id.city or '' ]], [[ company.partner_id.country_id.name or '' ]], [[ company.partner_id.zip or '' ]],</drawString>
            <drawString style="terp_default_left_9_Bold" x="13cm" y="28.2cm">Phone: [[ company.partner_id.phone or '' ]], Fax : [[ company.partner_id.fax or '' ]] </drawString>
            <drawString style="terp_default_right_9_Bold" x="13cm" y="27.8cm">CO. REG. NO.  [[ company.company_registry or '' ]]</drawString>
            <drawString style="terp_default_right_9_Bold" x="13cm" y="27.4cm">GST REG NO.   [[ company.gst_no or '' ]]</drawString>

            <!-- left margin -->
            <rotate degrees="90"/>
            <fill color="grey"/>
            <drawString x="2.65cm" y="-0.4cm">generated by Odoo.com</drawString>
            <fill color="black"/>
            <rotate degrees="-90"/>

            <!--page bottom-->
            <lines>1.2cm 2.65cm 19.9cm 2.65cm</lines>
            <place x="1.3cm" y="0cm" height="2.55cm" width="19.0cm">
                <para style="main_footer">[[ company.rml_footer ]]</para>
                <para style="main_footer">Contact : [[ user.name ]] - Page: <pageNumber/></para>
            </place>
        </pageGraphics>
    </pageTemplate>
    </header>
    """
    
    @api.v7
    def _get_header(self,cr,uid,ids):
        return self.header
    
    @api.v7
    def onchange_rml_paper_format(self, cr, uid, ids, rml_paper_format, context=None):
        if rml_paper_format == 'us_letter':
            return {'value': {'rml_header': self._header_letter}}
        return {'value': {'rml_header': self.header}}
    
    _defaults = {
        'rml_header':_get_header,
#         'rml_header2' : _get_header,
#         'rml_header3': _get_header,
    }
    